Repository Raghava-Chittidi/NUSTuts-Frontend, pull requests merged in 2024-07, with the labels that each got.

#88 fix: Fixed calendar select bug and files bug
  src/components/consultations/Calendar.tsx
  src/pages/files/WeekFilesPage.tsx
  src/util/util.ts
Labels: bug

#89 refactor: removed forgot password
  src/pages/LoginPage.tsx
Labels: bug

#90 feat: Improved error handling for auth
  src/hooks/useLogin.ts
  src/hooks/useStudentSignup.ts
  src/pages/LoginPage.tsx
  src/pages/student/StudentSignUpPage.tsx
Labels: enhancement

#91 fix: fixed files bug
  src/pages/files/WeekFilesPage.tsx
  tsconfig.json
Labels: enhancement

#92 Cleanup
  index.html
  public/NUSTUTS.svg
  public/vite.svg
  src/App.tsx
  src/components/Logout.tsx
  src/components/NavBar.tsx
  src/components/PrivateRoute.tsx
  src/components/attendance/Countdown.tsx
  src/components/attendance/StudentTodayAttendance.tsx
  src/components/attendance/StudentViewAttendance.tsx
  src/components/attendance/TATodayAttendance.tsx
  src/components/attendance/TAViewAttendance.tsx
  src/components/avatar/AvatarDisplay.tsx
  src/components/consultations/Calendar.tsx
  src/components/consultations/ConsultationBooking.tsx
  src/components/consultations/ConsultationBookingItem.tsx
  src/components/consultations/Consultations.tsx
  src/components/discussion/AllMessages.tsx
  src/components/discussion/MessageItem.tsx
  src/components/discussion/SendMessage.tsx
  src/components/files/FileUpload.tsx
  src/components/modules/ModuleListItem.tsx
  src/components/modules/ModuleTutorialListItem.tsx
  src/components/request/RequestListItem.tsx
  src/components/sidebar/AttendanceMenu.tsx
  src/components/sidebar/SidebarButton.tsx
  src/hooks/useTutorial.ts
  src/pages/ChooseUserType.tsx
  src/pages/Homepage.tsx
  src/pages/LoginPage.tsx
  src/pages/consultations/ViewConsultationPage.tsx
  src/pages/discussion/DiscussionPage.tsx
  src/pages/files/FilesPage.tsx
  src/pages/files/WeekFilesPage.tsx
  src/pages/student/ModuleTutorialsPage.tsx
  src/pages/student/ModulesPage.tsx
  src/pages/student/StudentSignUpPage.tsx
  src/pages/ta/RequestPage.tsx
  src/pages/tutorial/TutorialPage.tsx
  src/services/consultations.ts
  src/util/util.ts
Labels: enhancement

#94 docs: added comments
  src/context/AuthContext.tsx
Labels: documentation

#93 docs: add comments for pages
  README.md
  src/pages/Homepage.tsx
  src/pages/LoginPage.tsx
  src/pages/attendance/AttendancePage.tsx
  src/pages/attendance/ViewAttendancePage.tsx
  src/pages/consultations/BookConsultationPage.tsx
  src/pages/consultations/ViewConsultationPage.tsx
  src/pages/discussion/DiscussionPage.tsx
  src/pages/files/FilesPage.tsx
  src/pages/files/WeekFilesPage.tsx
  src/pages/student/ModuleTutorialsPage.tsx
  src/pages/student/ModulesPage.tsx
  src/pages/student/StudentSignUpPage.tsx
  src/pages/ta/RequestPage.tsx
  src/pages/tutorial/TutorialPage.tsx
  src/util/user.ts
  src/util/util.ts
Labels: documentation

#95 docs: added comments
  src/App.tsx
  src/context/AuthContext.tsx
  src/context/WebsocketContext.tsx
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useStudentSignup.ts
  src/hooks/useTutorial.ts
  src/pages/attendance/AttendancePage.tsx
  src/pages/attendance/ViewAttendancePage.tsx
  src/pages/consultations/ViewConsultationPage.tsx
  src/pages/discussion/DiscussionPage.tsx
  src/pages/files/WeekFilesPage.tsx
  src/pages/student/ModuleTutorialsPage.tsx
  src/pages/student/ModulesPage.tsx
  src/pages/ta/RequestPage.tsx
  src/pages/tutorial/TutorialPage.tsx
  src/types.ts
  src/util/user.ts
  src/util/util.ts
Labels: documentation

#97 fix: expired attendance code is valid
  src/components/attendance/Countdown.tsx
  src/components/attendance/StudentTodayAttendance.tsx
  src/components/attendance/StudentViewAttendance.tsx
  src/components/attendance/TATodayAttendance.tsx
  src/components/attendance/TAViewAttendance.tsx
  src/components/consultations/Calendar.tsx
  src/components/consultations/ConsultationBooking.tsx
  src/components/consultations/Consultations.tsx
Labels: bug

#98 fix: fixed attendance scrolling bug
  src/components/attendance/TATodayAttendance.tsx
  src/components/consultations/ConsultationBookingItem.tsx
  src/pages/consultations/ViewConsultationPage.tsx
  src/util/util.ts
Labels: bug

#99 fix: TA today attendance not displaying loading spinner when loading
  src/components/attendance/TATodayAttendance.tsx
Labels: bug

#100 fix: fixed padding for ta view attendance
  src/components/attendance/TAViewAttendance.tsx
Labels: bug
